<a href="https://colab.research.google.com/github/Rabbi1067/Machine-Learning-ML-/blob/main/Pandas_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

lnstall pandas

In [1]:
#pip install pandas

Import

In [2]:
import pandas as pd
import numpy as np

Create data frame

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"])

In [5]:
df.head()

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [6]:
df.tail()

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int64
 1   col2    5 non-null      int64
 2   col3    5 non-null      int64
 3   col4    5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes

In [9]:
df.describe()

            col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

Indexing

In [10]:
df[['col1','col2','col3']]

      col1  col2  col3
row1     0     1     2
row2     4     5     6
row3     8     9    10
row4    12    13    14
row5    16    17    18

In [11]:
df['col1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int64

In [12]:
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int64

In [13]:
df.loc[['row2','row3']]

      col1  col2  col3  col4
row2     4     5     6     7
row3     8     9    10    11

In [14]:
df.iloc[2:4,0:2]

      col1  col2
row3     8     9
row4    12    13

convert dataframe into arrays

In [15]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

Basic operation

In [16]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64